spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: bhz
    password: Bhz123456
    url: jdbc:mysql://localhost:3306/firstDoc?serverTimezone=UTC

mybatis:
  mapper-locations: classpath:/mapper/*.xml