server:
  port: 8911
spring:
  cloud:
    nacos:
      discovery:
        server-addr: http://localhost:8848
#      config:
#        shared-configs: application.yaml
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: bhz
    password: Bhz123456
    url: jdbc:mysql://localhost:3306/firstDoc?serverTimezone=UTC
  #  security:
#    user:
#      name: spring
#      password: spring_admin

  application:
    name: consumer