server:
  port: 8911
  servlet:
    context-path: /doc
spring:
  redis:
    port: 6379
    database: 0
    host: localhost

  cloud:
    nacos:
      discovery:
        server-addr: http://localhost:8848
  #      config:
  #        shared-configs: application.yaml
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: bhz
    password: Bhz123456
    url: jdbc:mysql://localhost:3306/firstDoc?serverTimezone=UTC
    hikari:
      connection-timeout: 30000
      maximum-pool-size: 15
      max-lifetime: 1800000
      minimum-idle: 5
      validation-timeout: 3000
      idle-timeout: 30000
      auto-commit: true
      connection-test-query: select 1
  #  security:
  #    user:
  #      name: spring
  #      password: spring_admin

  application:
    name: consumer
mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath:/mapper/*.xml
auth:
  server:
    base:
      url: http://localhost:8912/shop/show