server:
  port: 8915
spring:
  resources:
    static-locations: classpath:/static
  mvc:
    view:
      suffix: .html
      prefix: /
  application:
    name: provider
  cloud:
    nacos:
      discovery:
        server-addr: http://localhost:8848
      config:
        #       配置服务地址
        server-addr: http://localhost:8848
        #       配置服务的dataId前缀
        prefix: 1
    sentinel:
      transport:
        port: 8999
        dashboard: localhost:8211
  datasource:
    url: jdbc:mysql://localhost:3306/firstDoc?serverTimezone=UTC
    username: bhz
    password: Bhz123456
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath:/mapper/*.xml
#nacos:
#  config:
#    server-addr: 127.0.0.1:8848
wx:
  pay:
    appid: 123 # 公众账号id
    mchid: 11111222 # 商户号id
    key: test #商户号的支付key
    keyPath:  test #微信支付证书（退款、关闭订单 时需要）
    notifyUrl: /order/ask #支付通知地址（必须是外网可以访问的地址）
    refundUrl: test #退款通知地址（必须是外网可以访问的地址）